---
# System preparation tasks

- name: Ensure homepage user exists
  ansible.builtin.user:
    name: "{{ homepage_user }}"
    system: true
    shell: /bin/bash
    home: "{{ homepage_home_dir }}"
    create_home: true
    state: present

- name: Ensure homepage directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ homepage_user }}"
    group: "{{ homepage_group }}"
    mode: '0755'
  loop:
    - "{{ homepage_install_dir }}"
    - "{{ homepage_config_dir }}"
    - "{{ homepage_config_backup_dir }}"
    - "{{ homepage_home_dir }}/.local/share/pnpm"
    - "{{ homepage_home_dir }}/.cache"

- name: Check if homepage is installed
  ansible.builtin.stat:
    path: "{{ homepage_install_dir }}/package.json"
  register: homepage_package_json

- name: Get current homepage version
  ansible.builtin.slurp:
    src: /opt/homepage_version.txt
  register: current_version_file
  failed_when: false
  changed_when: false

- name: Set current homepage version fact
  ansible.builtin.set_fact:
    homepage_current_version: "{{ current_version_file.content | b64decode | trim if current_version_file.content is defined else 'unknown' }}"

- name: Display current homepage version
  ansible.builtin.debug:
    msg: "Current homepage version: {{ homepage_current_version }}"
    verbosity: 1
