#cloud-config
hostname: ${hostname}
package_update: true
package_upgrade: true

# Pacchetti base comuni a tutte le VM
packages:
  - qemu-guest-agent
  - curl
  - nano
  - openssh-server

# Utente principale
users:
  - name: ${default_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_pub_key}

# Comandi base comuni a tutte le VM
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl enable ssh
  - systemctl start ssh
