---
# Homepage Services - Static Configuration
      
- Management:
    - Cockpit:
        icon: cockpit.png
        href: https://192.168.6.101:9090/system
    - Grafana:
        icon: grafana.png
        href: http://192.168.6.105:3000

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.6.103:8096/


- Infrastructure:
    - Proxmox VE:
        icon: proxmox.png
        href: https://192.168.6.4:8006
        description: Proxmox VE Management Interface
        
    - HashiCorp Vault:
        icon: vault.png
        href: http://192.168.6.3:8200
        description: Secrets Management

# - Monitoring:
#     - Homepage Health:
#         icon: homepage.png
#         href: http://192.168.6.100:3000
#         description: This Dashboard
#         widget:
#           type: resources
#           cpu: true
#           memory: true
#           disk: /
