---
- name: Store arbitrary secret into Vault
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vault_mount_point: "terraform"

  tasks:
    - name: Require target KV path and data
      ansible.builtin.assert:
        that:
          - vault_kv_path is defined
          - vault_data is defined
        fail_msg: "Provide 'vault_kv_path' and 'vault_data' (dict) as variables."
      no_log: true

    - name: Write provided data to Vault KV v2
      community.hashi_vault.vault_kv2_write:
        url: "{{ lookup('env','VAULT_ADDR') }}"
        token: "{{ lookup('env','VAULT_TOKEN') }}"
        path: "{{ vault_kv_path }}"
        engine_mount_point: "{{ vault_mount_point }}"
        data: "{{ vault_data }}"
      delegate_to: localhost
      no_log: true
